"""empty message

Revision ID: e8b533b144d1
Revises: bd1bcd9ebd07
Create Date: 2021-08-14 13:18:30.816471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8b533b144d1'
down_revision = 'bd1bcd9ebd07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'date')
    # ### end Alembic commands ###
