"""students table

Revision ID: ec5b23fe9bb2
Revises: 
Create Date: 2021-08-11 15:35:09.812749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec5b23fe9bb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('surname', sa.String(length=120), nullable=True),
    sa.Column('room', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    op.create_index(op.f('ix_Students_name'), 'Students', ['name'], unique=False)
    op.create_index(op.f('ix_Students_surname'), 'Students', ['surname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Students_surname'), table_name='Students')
    op.drop_index(op.f('ix_Students_name'), table_name='Students')
    op.drop_table('Students')
    # ### end Alembic commands ###
